---
project:
  name: serverless-operator
  # For minor and major version bumps, bump all `dependencies.previous` to whatever `dependencies` has set.
  version: 1.28.0

olm:
  replaces: 1.27.0
  skipRange: '>=1.27.0 <1.28.0'
  channels:
    default: 'stable'
    list:
      - 'stable'

requirements:
  kube:
    # The min version validation in `vendor/knative.dev/pkg/version/version.go`
    # is ignored as it is overridden by fake version via KUBERNETES_MIN_VERSION.
    # This value is used for CSV's min version validation.
    minVersion: 1.21.0
  golang: '1.18'
  nodejs: 16.x
  ocpVersion:
    min: '4.8'
    max: '4.12'
    label: 'v4.8'

dependencies:
  serving: 1.7.0
  # serving midstream branch name
  serving_artifacts_branch: release-v1.7

  # versions for networking components
  kourier: 1.7.0
  net_kourier_artifacts_branch: release-1.7
  net_istio: 1.7.0
  net_istio_artifacts_branch: release-1.7
  maistra: 2.3-latest

  eventing: knative-v1.7
  # eventing core midstream branch name
  eventing_artifacts_branch: release-v1.7

  eventing_kafka: 1.1.0
  # eventing-kafka-broker promotion tag
  eventing_kafka_broker: knative-v1.7
  # eventing-kafka-broker midstream branch or commit
  eventing_kafka_broker_artifacts_branch: release-v1.7
  cli: 1.7.1
  func:
    util: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
    tekton_s2i: registry.redhat.io/ocp-tools-4-tech-preview/source-to-image-rhel8@sha256:98d8cb3a255641ca6a1bce854e5e2460c20de9fb9b28e3cc67eb459f122873dd
    tekton_buildah: registry.redhat.io/rhel8/buildah@sha256:a1e5cc0fb334e333e5eab69689223e8bd1f0c060810d260603b26cf8c0da2023
  operator: 1.5.2
  # Previous versions required for downgrade testing
  previous:
    serving: 1.6.0
    eventing: 1.6
    eventing_kafka: 1.1.0
    eventing_kafka_broker: 1.6
upgrade_sequence:
  - csv: serverless-operator.v1.25.0
    source: redhat-operators
    serving_cr: test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeserving_cr.yaml
    eventing_cr: test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeeventing_cr.yaml
  - csv: serverless-operator.v1.26.0
    source: redhat-operators
  - csv: serverless-operator.v1.27.0
    source: redhat-operators
  - csv: serverless-operator.v1.28.0
    source: serverless-operator
select_testsuite:
  - name: "Always"
    # Runs always because run_if_changed is omitted.
    testsuites:
      - name: serverless_operator_e2e_tests
        upstream: false
  - name: "Eventing Kafka"
    run_if_changed:
      - "^knative-operator/pkg/controller/knativekafka/"
      - "^knative-operator/pkg/webhook/knativekafka/"
    testsuites:
      - name: serverless_operator_kafka_e2e_tests
        upstream: false
      - name: downstream_knative_kafka_e2e_tests
        upstream: false
      - name: upstream_knative_eventing_kafka_e2e #TODO: Run this at all? Should this be removed?
        upstream: true
      - name: upstream_knative_eventing_kafka_broker_e2e
        upstream: true
  - name: "Eventing"
    run_if_changed:
      - "^knative-operator/pkg/controller/knativeeventing/"
      - "^knative-operator/pkg/webhook/knativeeventing/"
      - "^openshift-knative-operator/cmd/operator/kodata/knative-eventing/"
      - "^openshift-knative-operator/pkg/eventing/"
    testsuites:
      - name: downstream_eventing_e2e_tests
        upstream: false
      - name: upstream_knative_eventing_e2e
        upstream: true
  - name: "Monitoring"
    run_if_changed:
      - "^knative-operator/pkg/monitoring/"
      - "^openshift-knative-operator/cmd/operator/kodata/monitoring/"
      - "^openshift-knative-operator/pkg/monitoring/"
    testsuites:
      - name: downstream_monitoring_e2e_tests
        upstream: false
  - name: "Serving"
    run_if_changed:
      - "^knative-operator/pkg/controller/knativeserving/"
      - "^knative-operator/pkg/webhook/knativeserving/"
      - "^openshift-knative-operator/cmd/operator/kodata/knative-serving/"
      - "^openshift-knative-operator/pkg/serving/"
      - "^serving/ingress/"
    testsuites:
      - name: downstream_serving_e2e_tests
        upstream: false
  - name: "UI"
    run_if_changed:
      - "^ui/"
    testsuites:
      - name: ui_tests
        upstream: false
  - name: "No tests"
    # No test suites will be run for the changes below.
    run_if_changed:
      - "^.github/"
      - "^docs/"
      - "^hack/generate/"
      - "^hack/patches/"
      - "\\.(md|adoc)$"
      - "^(README|LICENSE)$"
      - "^(OWNERS|OWNERS_ALIASES)$"
    testsuites: null

#  - name: "test/ui" # UI tests run in separate Prow job.
#  - name: "test/upgrade" # Upgrade tests are run in separate Prow job.

# All test suites would be run if there's a change in paths that is not listed above.
# E.g. for changes in hack, olm-catalog, openshift, vendor, test etc.

# TODO: Divide the upgrade test suite? Then we could run some parts based on changes

