schema: olm.channel
name: stable
package: serverless-operator
entries:
  - name: "serverless-operator.v1.22.0"
  - name: "serverless-operator.v1.23.0"
    replaces: serverless-operator.v1.22.0
    skipRange: ">=1.22.0 <1.23.0"
